registries:
  - registry.redhat.io
  - brew.registry.redhat.io
  - quay.io/opendatahub
  - quay.io/modh
  - registry.access.redhat.com
  - image-registry.openshift-image-registry.svc

pypi_mirrors:
  - https://pypi.corp.redhat.com/simple/

bundled_packages:
  - codeflare-sdk
  - odh-manifest
  - opendatahub-operator
