name: Disconnected Readiness
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@a03726c8a7dd37b0c27105c2a67395c16c3f74b9
    with:
      rules: ""
